# .github/workflows/security-scan.yml
name: Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  security:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl wget unzip
          pip install checkov
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Run Checkov
        run: checkov -d .

      - name: Run Trivy for IaC Scanning
        run: trivy iac --severity HIGH,CRITICAL --no-progress -f table -o trivy-security-report.txt .

      - name: Upload Trivy Security Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-security-report
          path: trivy-security-report.txt
