name: Generate terraform docs
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/**/*.tf'
      - '.terraform-docs.yml'
      - '.github/workflows/terraform-docs.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside modules
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: .
        recursive: true
        recursive-path: modules
        output-file: README.md
        output-method: inject
        git-push: "true"
