name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  terraform:
    name: Terraform Lint, Validate, and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl wget unzip
          # Install TFLint
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          # Install Checkov
          pip install checkov
          # Install Trivy
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        run: tflint

      - name: Run Checkov
        run: checkov -d .

      - name: Run Trivy for IaC Scanning
        run: trivy iac --severity HIGH,CRITICAL --no-progress -f table -o trivy-report.txt .

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Generate Documentation with Terraform-docs
        run: terraform-docs markdown table . > README.md
