name: Terratest Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Initialize Go Module
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/HalcyonOps/terraform-aws-modules
          fi

      - name: Install Dependencies
        run: |
          go mod tidy
          # Alternatively, specify required modules
          # go install github.com/gruntwork-io/terratest/modules/terraform@latest
          # go install github.com/stretchr/testify/assert@latest

      - name: Run Terratest for EC2 Module
        run: |
          cd modules/compute/ec2/tests
          go test -v -timeout 30m

      - name: Run Terratest for VPC Module
        run: |
          cd modules/network/vpc/tests
          go test -v -timeout 30m
