name: Terraform Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.tf'
      - '.github/workflows/terraform-validate.yml'

permissions:
  contents: read
  pull-requests: write
  issues: read
  checks: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.5.0

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init & Validate
        run: |
          find . -type f -name "*.tf" -not -path "**/.terraform/*" -exec dirname {} \; | sort -u | while read dir; do
            echo "Validating $dir"
            cd $dir
            terraform init -backend=false
            terraform validate
            cd -
          done
